let src=[],cand=[],accepted=[],rejected=[],finalRows=[];const $=x=>document.getElementById(x);
const norm=s=>(s??"").toString().normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/\s+/g," ").trim();
const get=(r,ns)=>{for(const n of ns){const k=Object.keys(r).find(k=>norm(k)===norm(n));if(k)return r[k]}return ""};
const relato=r=>norm(get(r,["relato","descripcion","narrativa","hecho"]));
const car=r=>norm(get(r,["analisis_caratula","caratula"]));
const V=/\b(AUTOMOVIL|VEHICULO|RODADO|CAMIONETA|CAMION|UTILITARIO|FURGON|SEDAN|COCHE)\b/;
const S=/\b(SUSTRA(?:E|EN|JO|JERON|IDO|IDA)|ROBA(?:N|RON|DO|DA)?|APODERA(?:N|RON)?|SE LLEV(?:A|AN|ARON)|NO SE ENCONTRABA|YA NO (?:SE )?ENCONTRABA)\b/;
const R=/\b(HALLA(?:DO|DA|RON|N)?|LOCALIZA(?:DO|DA|RON|N)?|RECUPERA(?:DO|DA|RON|N)?|DAN CON (?:EL|LA) (?:VEHICULO|RODADO|AUTO|CAMIONETA)|VEHICULO ABANDONADO|RODADO ABANDONADO|PEDIDO DE SECUESTRO(?: ACTIVO)?)\b/;
const PART=/\b(CHAPA PATENTE|PATENTE|RUEDA|CUBIERTA|AUXILIO|BATERIA|ESTEREO|AUTOPARTE|PERTENENCIAS)\b/;
const MOTO=/\b(MOTO|MOTOCICLETA|MOTOVEHICULO|CICLOMOTOR)\b/;
function near(t,a,b,d=140){for(const ma of t.matchAll(new RegExp(a.source,"g"))){const z=t.slice(Math.max(0,ma.index-d),ma.index+d);if(b.test(z))return true}return false}
function filter1(r){const t=relato(r),c=car(r);if(!t)return null;const vehicle=V.test(t)||/AUTOMOTOR/.test(c);const event=S.test(t)||R.test(t)||/SUSTRA[C]?CION AUTOMOTOR|HALLAZGO AUTOMOTOR/.test(c);if(!vehicle||!event)return null;if(MOTO.test(t)&&!V.test(t)&&!/AUTOMOTOR/.test(c))return null;return {...r,ETAPA_1:"CANDIDATO",MOTIVO_1:"Mención de automotor + evento compatible; requiere auditoría contextual."}}
function filter2(r){const t=relato(r),c=car(r);const sv=near(t,V,S)||near(t,S,V),rv=near(t,V,R)||near(t,R,V);const strongHall=/\b(VEHICULO|RODADO|AUTOMOVIL|CAMIONETA)\b.{0,180}\b(PEDIDO DE SECUESTRO|ABANDONAD[OA]|HALLAD[OA]|LOCALIZAD[OA])\b/.test(t)||/\b(PEDIDO DE SECUESTRO|ABANDONAD[OA]|HALLAD[OA]|LOCALIZAD[OA])\b.{0,180}\b(VEHICULO|RODADO|AUTOMOVIL|CAMIONETA)\b/.test(t);
 if(sv&&rv)return {ok:true,cond:"INMEDIATO",why:"Dos eventos vinculados al automotor: sustracción y recuperación/localización."};
 if(sv&&!rv){if(PART.test(t)&&!near(t,S,V,80))return {ok:false,why:"La acción parece referirse a patente/autoparte/pertenencias, no al rodado completo."};return {ok:true,cond:"SUSTRAIDO",why:"Sustracción vinculada contextualmente al automotor, sin recuperación en la secuencia."}}
 if(!sv&&(rv||strongHall)&&(/HALLAZGO AUTOMOTOR/.test(c)||strongHall))return {ok:true,cond:"HALLAZGO",why:"Hallazgo/localización vinculada al automotor sin sustracción actual narrada."};
 return {ok:false,why:"No se pudo vincular con suficiente fuerza la acción de sustracción/hallazgo al automotor."}
}
function extract(r){const t=norm(get(r,["relato","descripcion","narrativa","hecho"]));const pick=res=>{for(const re of res){const m=t.match(re);if(m)return m[1].trim()}return ""};return {...r,MARCA:"",MODELO:"",PATENTE:pick([/\bDOMINIO\s*(?:NRO|N°|NUMERO)?\s*[:\-]?\s*([A-Z]{2,3}\s?\d{3}\s?[A-Z]{0,2}|[A-Z]{3}\s?\d{3})\b/,/\bPATENTE\s*(?:NRO|N°|NUMERO)?\s*[:\-]?\s*([A-Z0-9]{6,9})\b/]),MOTOR:pick([/\b(?:NUMERO DE MOTOR|MOTOR(?: NRO| N°| NUMERO)?)\s*[:\-]?\s*([A-Z0-9.-]{4,25})\b/]),CHASIS:pick([/\b(?:NUMERO DE CHASIS|CHASIS(?: NRO| N°| NUMERO)?)\s*[:\-]?\s*([A-Z0-9.-]{6,30})\b/])}}
$("file").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{$("status").textContent="Leyendo "+f.name+"…";await tick();if(typeof XLSX==="undefined")throw new Error("No se cargó la librería XLSX.");const buf=await f.arrayBuffer();$("status").textContent="Interpretando Excel…";await tick();const wb=XLSX.read(buf,{type:"array"});if(!wb.SheetNames.length)throw new Error("El Excel no contiene hojas.");const ws=wb.Sheets[wb.SheetNames[0]];src=XLSX.utils.sheet_to_json(ws,{defval:"",raw:false});cand=[];accepted=[];rejected=[];finalRows=[];$("f1").disabled=!src.length;$("f2").disabled=$("f3").disabled=true;["d1","d2","d3"].forEach(x=>$(x).disabled=true);$("status").textContent=src.length.toLocaleString("es-AR")+" denuncias cargadas. Presioná 1️⃣ Detectar candidatos."}catch(err){$("status").textContent="❌ Error al cargar: "+err.message;console.error(err)}};
$("f1").onclick=async()=>{try{lock(true);cand=[];for(let i=0;i<src.length;i++){const x=filter1(src[i]);if(x)cand.push(x);if(i%300===0){$("status").textContent="Filtro 1 procesando… "+Math.round(i/src.length*100)+"%";await tick()}}$("f2").disabled=!cand.length;$("d1").disabled=!cand.length;show(cand,"ETAPA_1","Filtro 1 terminado: "+cand.length+" candidatos de "+src.length+".")}catch(err){$("status").textContent="❌ Error en Filtro 1: "+err.message;console.error(err)}finally{lock(false)}};
$("f2").onclick=async()=>{try{lock(true);accepted=[];rejected=[];for(let i=0;i<cand.length;i++){const r=cand[i],x=filter2(r);(x.ok?accepted:rejected).push({...r,CONDICION_AUDITOR:x.cond||"DESCARTADO",MOTIVO_2:x.why});if(i%200===0){$("status").textContent="Filtro 2 procesando… "+Math.round(i/cand.length*100)+"%";await tick()}}$("f3").disabled=!accepted.length;$("d2").disabled=false;show(accepted,"CONDICION_AUDITOR",`Filtro 2 terminado: ${accepted.length} aceptados; ${rejected.length} descartados.`)}catch(err){$("status").textContent="❌ Error en Filtro 2: "+err.message;console.error(err)}finally{lock(false)}};
$("f3").onclick=()=>{finalRows=accepted.map(extract);$("d3").disabled=!finalRows.length;show(finalRows,"CONDICION_AUDITOR","Filtro 3: "+finalRows.length+" casos finales. Marca/modelo quedan pendientes de reglas validadas; patente/motor/chasis son extracción inicial.")};
function show(arr,key,msg){$("status").textContent=msg;const ct={};arr.forEach(r=>ct[r[key]]=(ct[r[key]]||0)+1);$("summary").innerHTML=Object.entries(ct).map(([k,v])=>`<div class="pill">${k}: ${v}</div>`).join("");$("rows").innerHTML=arr.slice(0,1000).map(r=>`<tr><td>${esc(r[key])}</td><td>${esc(get(r,["numero_interno","nro_interno","numero interno"]))}</td><td>${esc(get(r,["analisis_caratula","caratula"]))}</td><td>${esc(r.MOTIVO_2||r.MOTIVO_1||"")}</td><td class="relato">${esc(get(r,["relato","descripcion","narrativa","hecho"]))}</td></tr>`).join("")}
function dl(rows,name,sheets){const wb=XLSX.utils.book_new();for(const [sn,rs] of sheets||[["RESULTADO",rows]])XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rs),sn);XLSX.writeFile(wb,name)}
$("d1").onclick=()=>dl(cand,"FILTRO_1_CANDIDATOS.xlsx");$("d2").onclick=()=>dl(null,"FILTRO_2_AUDITORIA.xlsx",[["ACEPTADOS",accepted],["DESCARTADOS",rejected]]);$("d3").onclick=()=>dl(finalRows,"AUDITORIA_AUTOMOTORES_FINAL.xlsx");
function esc(v){return (v??"").toString().replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function tick(){return new Promise(r=>setTimeout(r,0))}
function lock(on){$("file").disabled=on;$("f1").disabled=on||!src.length;$("f2").disabled=on||!cand.length;if(on)$("f3").disabled=true}
window.addEventListener("error",e=>{$("status").textContent="❌ Error de la aplicación: "+e.message});
